version: "3.7"

services:

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: quiz_db
    env_file:
      - .env
    ports:
      - "5435:5432"

volumes:
  postgres_data:
