version: "3.7"

services:

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: quiz_db
    env_file:
      - .env
    ports:
      - "5435:5432"

  fastapi:
    container_name: backend
    build: ./backend
    command: sh -c "uvicorn app:app --reload --host 0.0.0.0"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
